name: Build docker and upload to registry

on:
  push:
    branches:
      - 'main'
      - 'fix-image-build'
    tags:
      # strict semver regex
      - v[0-9]+.[0-9]+.[0-9]+

env:
  CIRCLES_CI_DO_TOKEN: ${{ secrets.CIRCLES_CI_DO_TOKEN }}

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-18.04
    steps:
      - name: Install dependencies
        run: |
          sudo snap install doctl
          sudo snap connect doctl:dot-docker
      - name: Configure auth
        run: |
          doctl auth init -t ${CIRCLES_CI_DO_TOKEN}
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: main
      - name: Get ref
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" 
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/*/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/*/}
          echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
        id: parse_ref
      - name: Build base image
        run: |
          echo $SOURCE_NAME
          echo $SOURCE_BRANCH
          echo $SOURCE_TAG
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
        env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
      - name: Docker build and tag
        env:
          IMAGE_VERSION: ${{ steps.parse_ref.outputs.tag }}
        run: |
          echo $IMAGE_VERSION
          echo ${{ env.IMAGE_VERSION }}
          docker build -t registry.digitalocean.com/circles-registry/subgraph:${IMAGE_VERSION} .
      - name: Registry login
        run: |
          doctl registry login
      - name: Docker push
        env:
          IMAGE_VERSION: ${{ steps.parse_ref.outputs.tag }}
        run: |
          docker push registry.digitalocean.com/circles-registry/subgraph:${IMAGE_VERSION}
